# action.yml
name: 'cargo contracts'
description: 'Cargo command wrapper'
inputs:
  cargo-cmd:  # id of input
    description: 'Cargo command'
    required: true
    default: 'versions.sh'
  working-directory:
    description: 'default work dir'
    required: true
    default: '.'
runs:
  using: 'docker'
  image: docker://openactionrs/action-cargo:r3.0.2
  args:
    - ${{inputs.working-directory}}
    - ${{inputs.cargo-cmd}}
